repos:
  - repo: local
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [ cython, pyi, python ]
        minimum_pre_commit_version: '2.9.2'
        additional_dependencies: [ 'isort==5.10.1' ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          [
            "--select=F",
            "--max-line-length=88",
            "--per-file-ignores=__init__.py:F401",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
  - repo: local
    hooks:
      - id: export-requirements
        name: Export requeriments.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.18.0
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: ['.[jinjafmt]']
